---

- name: Setup Monitor containers
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Read vars
      ansible.builtin.include_vars:
        file: ../variables/git.yml

    - name: Docker Compose up
      community.docker.docker_compose_v2:
        project_src: "{{ infra_repo_dir }}/monitor"
