api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

metrics:
  prometheus: true
  
providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/configs.yml

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
    #http:
    #  middlewares:
    #    - redirect-www-to-non-www@file
  
  #mysql:
  #  address: ':3306'

certificatesResolvers:
  le:
    acme:
      email: juand.diazd@gmail.com
      storage: /letsencrypt/acme.json
      httpchallenge:
        entrypoint: web
