---
- name: Converge Run
  hosts: all
  gather_facts: false
  tasks:
    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"

# - name: OS
#   ansible.builtin.import_playbook: croma.base.os

# - name: My Playbook
#   ansible.builtin.import_playbook: croma.base.sample

# - name: Variables
#   ansible.builtin.import_playbook: croma.base.read_vars

- name: Server set-up
  ansible.builtin.import_playbook: croma.base.setup
