[local]
localhost ansible_connection=local

[all]
local ansible_connection=local ansible_host=127.0.0.1 ansible_user=juan
#node1 ansible_host=192.168.18.131 ansible_user=garis ansible_ssh_common_args='-o StrictHostKeyChecking=no'
